### ISSUE TITLE
[feat]: Allow basic type constants in config

### ISSUE THREAD

**Issue by SkeLLLa** [stephenh/ts-app-env#11]
Sometimes in apps it may require to have deeply nested configuration. And alongside properties from env it is necessary to put some constants to simplify further usage of the configuration object.

Example:

```ts
import { newConfig, number } from 'ts-app-env';

const template = {
  some: {
    config: {
      nested: {
        propertyA: number('ENV_VAR_PROPERTY_A'),
        propertyB: 42
      }
    }
  } as ISomeConfigInterface
}

export const config = newConfig(template, process.env);

const foo = new Some(config.some)
```

Currently `propertyB` will be in `config` type and will have a type `number`. But actually it will be ignored because of https://github.com/stephenh/ts-app-env/blob/main/src/index.ts#L46.

My suggestion is to add extra typeof check for basic types like `boolean`, `string`, `number` and pass such values "as-is", to make this as single source of truth for configuration and avoid extra config files with constants.

Currently it is possible through `option`
```ts
function constant<T>(value: T): T {
  return option<T>({ default: value }, () => {
    return value;
  });
}
```

But simply passing a value will be much easier.

**Comment by stephenh** [comment]
Hey @SkeLLLa , thanks for filing the issue! I'd actually kinda forgotten about the capability to use nested configs (we used it at a prior company I was at, but haven't been using it at the some I'm at now).

Afaict your analysis is spot on; if you wanted to file a PR to fix this issue, that would be great! Thanks!
